// This file is auto-generated. DO NOT EDIT

package slack

// These constants match the scopes provided by Slack API
const (
	ChannelsHistoryScope   = "channels:history"
	ChannelsReadScope      = "channels:read"
	ChannelsWriteScope     = "channels:write"
	ChatWriteBotScope      = "chat:write:bot"
	ChatWriteUserScope     = "chat:write:user"
	DndReadScope           = "dnd:read"
	DndWriteScope          = "dnd:write"
	EmojiReadScope         = "emoji:read"
	FilesReadScope         = "files:read"
	FilesWriteUserScope    = "files:write:user"
	GroupsHistoryScope     = "groups:history"
	GroupsReadScope        = "groups:read"
	GroupsWriteScope       = "groups:write"
	IdentityBasicScope     = "identity.basic"
	ImHistoryScope         = "im:history"
	ImReadScope            = "im:read"
	ImWriteScope           = "im:write"
	LinksWriteScope        = "links:write"
	MpimHistoryScope       = "mpim:history"
	MpimReadScope          = "mpim:read"
	MpimWriteScope         = "mpim:write"
	PinsReadScope          = "pins:read"
	PinsWriteScope         = "pins:write"
	ReactionsReadScope     = "reactions:read"
	ReactionsWriteScope    = "reactions:write"
	RemindersReadScope     = "reminders:read"
	RemindersWriteScope    = "reminders:write"
	SearchReadScope        = "search:read"
	StarsReadScope         = "stars:read"
	StarsWriteScope        = "stars:write"
	TeamReadScope          = "team:read"
	UsergroupsReadScope    = "usergroups:read"
	UsergroupsWriteScope   = "usergroups:write"
	UsersProfileReadScope  = "users.profile:read"
	UsersProfileWriteScope = "users.profile:write"
	UsersReadScope         = "users:read"
	UsersWriteScope        = "users:write"
)
