package slack

// Auto-generated by internal/cmd/genmethods/genmethods.go. DO NOT EDIT!

// AuthService handles Auth related endpoints
type AuthService struct {
	client *httpClient
	token  string
}

// BotsService handles Bots related endpoints
type BotsService struct {
	client *httpClient
	token  string
}

// ChannelsService handles Channels related endpoints
type ChannelsService struct {
	client *httpClient
	token  string
}

// ChatService handles Chat related endpoints
type ChatService struct {
	client *httpClient
	token  string
}

// DialogService handles Dialog related endpoints
type DialogService struct {
	client *httpClient
	token  string
}

// EmojiService handles Emoji related endpoints
type EmojiService struct {
	client *httpClient
	token  string
}

// GroupsService handles Groups related endpoints
type GroupsService struct {
	client *httpClient
	token  string
}

// OAuthService handles OAuth related endpoints
type OAuthService struct {
	client *httpClient
	token  string
}

// RTMService handles RTM related endpoints
type RTMService struct {
	client *httpClient
	token  string
}

// ReactionsService handles Reactions related endpoints
type ReactionsService struct {
	client *httpClient
	token  string
}

// RemindersService handles Reminders related endpoints
type RemindersService struct {
	client *httpClient
	token  string
}

// UsergroupsService handles Usergroups related endpoints
type UsergroupsService struct {
	client *httpClient
	token  string
}

// UsergroupsUsersService handles UsergroupsUsers related endpoints
type UsergroupsUsersService struct {
	client *httpClient
	token  string
}

// UsersService handles Users related endpoints
type UsersService struct {
	client *httpClient
	token  string
}

// UsersProfileService handles UsersProfile related endpoints
type UsersProfileService struct {
	client *httpClient
	token  string
}
