package slack

// Auto-generated by internal/cmd/genmethods/genmethods.go (generateServiceDetailsFile). DO NOT EDIT!

import (
	"context"
	"encoding/json"
	"net/url"
	"strconv"
	"strings"

	"github.com/lestrrat-go/slack/objects"
	"github.com/pkg/errors"
)

var _ = strconv.Itoa
var _ = strings.Index
var _ = json.Marshal
var _ = objects.EpochTime(0)

// UsersProfileGetCall is created by UsersProfileService.Get method call
type UsersProfileGetCall struct {
	service       *UsersProfileService
	includeLabels bool
	user          string
}

// UsersProfileSetCall is created by UsersProfileService.Set method call
type UsersProfileSetCall struct {
	service *UsersProfileService
	name    string
	profile *objects.UserProfile
	user    string
	value   string
}

// Get creates a UsersProfileGetCall object in preparation for accessing the users.profile.get endpoint
func (s *UsersProfileService) Get() *UsersProfileGetCall {
	var call UsersProfileGetCall
	call.service = s
	return &call
}

// IncludeLabels sets the value for optional includeLabels parameter
func (c *UsersProfileGetCall) IncludeLabels(includeLabels bool) *UsersProfileGetCall {
	c.includeLabels = includeLabels
	return c
}

// User sets the value for optional user parameter
func (c *UsersProfileGetCall) User(user string) *UsersProfileGetCall {
	c.user = user
	return c
}

// ValidateArgs checks that all required fields are set in the UsersProfileGetCall object
func (c *UsersProfileGetCall) ValidateArgs() error {
	return nil
}

// Values returns the UsersProfileGetCall object as url.Values
func (c *UsersProfileGetCall) Values() (url.Values, error) {
	if err := c.ValidateArgs(); err != nil {
		return nil, errors.Wrap(err, `failed validation`)
	}
	v := url.Values{}
	v.Set(`token`, c.service.token)

	if c.includeLabels {
		v.Set("include_labels", "true")
	}

	if len(c.user) > 0 {
		v.Set("user", c.user)
	}
	return v, nil
}

type UsersProfileGetCallResponse interface {
	OK() bool
	ReplyTo() int
	Error() *objects.ErrorResponse
	Timestamp() string
}

type usersProfileGetCallResponseProxy struct {
	OK        bool                   `json:"ok"`
	ReplyTo   int                    `json:"reply_to"`
	Error     *objects.ErrorResponse `json:"error"`
	Timestamp string                 `json:"ts"`
	Payload0  json.RawMessage        `json:"-"`
}
type usersProfileGetCallResponse struct {
	ok      bool
	replyTo int
	error   *objects.ErrorResponse
	ts      string
}
type UsersProfileGetCallResponseBuilder struct {
	resp *usersProfileGetCallResponse
}

func BuildUsersProfileGetCallResponse() *UsersProfileGetCallResponseBuilder {
	return &UsersProfileGetCallResponseBuilder{resp: &usersProfileGetCallResponse{}}
}
func (v *usersProfileGetCallResponse) OK() bool {
	return v.ok
}
func (v *usersProfileGetCallResponse) ReplyTo() int {
	return v.replyTo
}
func (v *usersProfileGetCallResponse) Error() *objects.ErrorResponse {
	return v.error
}
func (v *usersProfileGetCallResponse) Timestamp() string {
	return v.ts
}
func (b *UsersProfileGetCallResponseBuilder) OK(v bool) *UsersProfileGetCallResponseBuilder {
	b.resp.ok = v
	return b
}
func (b *UsersProfileGetCallResponseBuilder) ReplyTo(v int) *UsersProfileGetCallResponseBuilder {
	b.resp.replyTo = v
	return b
}
func (b *UsersProfileGetCallResponseBuilder) Error(v *objects.ErrorResponse) *UsersProfileGetCallResponseBuilder {
	b.resp.error = v
	return b
}
func (b *UsersProfileGetCallResponseBuilder) Timestamp(v string) *UsersProfileGetCallResponseBuilder {
	b.resp.ts = v
	return b
}
func (b *UsersProfileGetCallResponseBuilder) Build() UsersProfileGetCallResponse {
	v := b.resp
	b.resp = &usersProfileGetCallResponse{}
	return v
}
func (r *usersProfileGetCallResponseProxy) parse(data []byte) error {
	if err := json.Unmarshal(data, r); err != nil {
		return errors.Wrap(err, `failed to unmarshal UsersProfileGetCallResponse`)
	}
	r.Payload0 = data
	return nil
}
func (r *usersProfileGetCallResponseProxy) payload() (*objects.UserProfile, error) {
	var res0 objects.UserProfile
	if err := json.Unmarshal(r.Payload0, &res0); err != nil {
		return nil, errors.Wrap(err, `failed to ummarshal objects.UserProfile from response`)
	}
	return &res0, nil
}
func (r *usersProfileGetCallResponse) MarshalJSON() ([]byte, error) {
	var p usersProfileGetCallResponseProxy
	p.OK = r.ok
	p.ReplyTo = r.replyTo
	p.Error = r.error
	p.Timestamp = r.ts
	return json.Marshal(p)
}

// Do executes the call to access users.profile.get endpoint
func (c *UsersProfileGetCall) Do(ctx context.Context) (*objects.UserProfile, error) {
	const endpoint = "users.profile.get"
	v, err := c.Values()
	if err != nil {
		return nil, err
	}
	var res usersProfileGetCallResponseProxy
	if err := c.service.client.postForm(ctx, endpoint, v, &res); err != nil {
		return nil, errors.Wrap(err, `failed to post to users.profile.get`)
	}
	if !res.OK {
		var err error
		if errresp := res.Error; errresp != nil {
			err = errors.New(errresp.String())
		} else {
			err = errors.New(`unknown error while posting to users.profile.get`)
		}
		return nil, err
	}

	return res.payload()
}

// FromValues parses the data in v and populates `c`
func (c *UsersProfileGetCall) FromValues(v url.Values) error {
	var tmp UsersProfileGetCall
	if raw := strings.TrimSpace(v.Get("include_labels")); len(raw) > 0 {
		parsed, err := strconv.ParseBool(raw)
		if err != nil {
			return errors.Wrap(err, `failed to parse boolean value "include_labels"`)
		}
		tmp.includeLabels = parsed
	}
	if raw := strings.TrimSpace(v.Get("user")); len(raw) > 0 {
		tmp.user = raw
	}
	*c = tmp
	return nil
}

// Set creates a UsersProfileSetCall object in preparation for accessing the users.profile.set endpoint
func (s *UsersProfileService) Set() *UsersProfileSetCall {
	var call UsersProfileSetCall
	call.service = s
	return &call
}

// Name sets the value for optional name parameter
func (c *UsersProfileSetCall) Name(name string) *UsersProfileSetCall {
	c.name = name
	return c
}

// Profile sets the value for optional profile parameter
func (c *UsersProfileSetCall) Profile(profile *objects.UserProfile) *UsersProfileSetCall {
	c.profile = profile
	return c
}

// User sets the value for optional user parameter
func (c *UsersProfileSetCall) User(user string) *UsersProfileSetCall {
	c.user = user
	return c
}

// Value sets the value for optional value parameter
func (c *UsersProfileSetCall) Value(value string) *UsersProfileSetCall {
	c.value = value
	return c
}

// ValidateArgs checks that all required fields are set in the UsersProfileSetCall object
func (c *UsersProfileSetCall) ValidateArgs() error {
	return nil
}

// Values returns the UsersProfileSetCall object as url.Values
func (c *UsersProfileSetCall) Values() (url.Values, error) {
	if err := c.ValidateArgs(); err != nil {
		return nil, errors.Wrap(err, `failed validation`)
	}
	v := url.Values{}
	v.Set(`token`, c.service.token)

	if len(c.name) > 0 {
		v.Set("name", c.name)
	}

	if c.profile != nil {
		profileEncoded, err := json.Marshal(c.profile)
		if err != nil {
			return nil, errors.Wrap(err, `failed to encode field`)
		}
		v.Set("profile", string(profileEncoded))
	}

	if len(c.user) > 0 {
		v.Set("user", c.user)
	}

	if len(c.value) > 0 {
		v.Set("value", c.value)
	}
	return v, nil
}

type UsersProfileSetCallResponse interface {
	OK() bool
	ReplyTo() int
	Error() *objects.ErrorResponse
	Timestamp() string
}

type usersProfileSetCallResponseProxy struct {
	OK        bool                   `json:"ok"`
	ReplyTo   int                    `json:"reply_to"`
	Error     *objects.ErrorResponse `json:"error"`
	Timestamp string                 `json:"ts"`
	Payload0  json.RawMessage        `json:"-"`
}
type usersProfileSetCallResponse struct {
	ok      bool
	replyTo int
	error   *objects.ErrorResponse
	ts      string
}
type UsersProfileSetCallResponseBuilder struct {
	resp *usersProfileSetCallResponse
}

func BuildUsersProfileSetCallResponse() *UsersProfileSetCallResponseBuilder {
	return &UsersProfileSetCallResponseBuilder{resp: &usersProfileSetCallResponse{}}
}
func (v *usersProfileSetCallResponse) OK() bool {
	return v.ok
}
func (v *usersProfileSetCallResponse) ReplyTo() int {
	return v.replyTo
}
func (v *usersProfileSetCallResponse) Error() *objects.ErrorResponse {
	return v.error
}
func (v *usersProfileSetCallResponse) Timestamp() string {
	return v.ts
}
func (b *UsersProfileSetCallResponseBuilder) OK(v bool) *UsersProfileSetCallResponseBuilder {
	b.resp.ok = v
	return b
}
func (b *UsersProfileSetCallResponseBuilder) ReplyTo(v int) *UsersProfileSetCallResponseBuilder {
	b.resp.replyTo = v
	return b
}
func (b *UsersProfileSetCallResponseBuilder) Error(v *objects.ErrorResponse) *UsersProfileSetCallResponseBuilder {
	b.resp.error = v
	return b
}
func (b *UsersProfileSetCallResponseBuilder) Timestamp(v string) *UsersProfileSetCallResponseBuilder {
	b.resp.ts = v
	return b
}
func (b *UsersProfileSetCallResponseBuilder) Build() UsersProfileSetCallResponse {
	v := b.resp
	b.resp = &usersProfileSetCallResponse{}
	return v
}
func (r *usersProfileSetCallResponseProxy) parse(data []byte) error {
	if err := json.Unmarshal(data, r); err != nil {
		return errors.Wrap(err, `failed to unmarshal UsersProfileSetCallResponse`)
	}
	r.Payload0 = data
	return nil
}
func (r *usersProfileSetCallResponseProxy) payload() (*objects.UserProfile, error) {
	var res0 objects.UserProfile
	if err := json.Unmarshal(r.Payload0, &res0); err != nil {
		return nil, errors.Wrap(err, `failed to ummarshal objects.UserProfile from response`)
	}
	return &res0, nil
}
func (r *usersProfileSetCallResponse) MarshalJSON() ([]byte, error) {
	var p usersProfileSetCallResponseProxy
	p.OK = r.ok
	p.ReplyTo = r.replyTo
	p.Error = r.error
	p.Timestamp = r.ts
	return json.Marshal(p)
}

// Do executes the call to access users.profile.set endpoint
func (c *UsersProfileSetCall) Do(ctx context.Context) (*objects.UserProfile, error) {
	const endpoint = "users.profile.set"
	v, err := c.Values()
	if err != nil {
		return nil, err
	}
	var res usersProfileSetCallResponseProxy
	if err := c.service.client.postForm(ctx, endpoint, v, &res); err != nil {
		return nil, errors.Wrap(err, `failed to post to users.profile.set`)
	}
	if !res.OK {
		var err error
		if errresp := res.Error; errresp != nil {
			err = errors.New(errresp.String())
		} else {
			err = errors.New(`unknown error while posting to users.profile.set`)
		}
		return nil, err
	}

	return res.payload()
}

// FromValues parses the data in v and populates `c`
func (c *UsersProfileSetCall) FromValues(v url.Values) error {
	var tmp UsersProfileSetCall
	if raw := strings.TrimSpace(v.Get("name")); len(raw) > 0 {
		tmp.name = raw
	}
	if raw := strings.TrimSpace(v.Get("profile")); len(raw) > 0 {
		if err := json.Unmarshal([]byte(raw), &tmp.profile); err != nil {
			return errors.Wrap(err, `failed to decode value "profile"`)
		}
	}
	if raw := strings.TrimSpace(v.Get("user")); len(raw) > 0 {
		tmp.user = raw
	}
	if raw := strings.TrimSpace(v.Get("value")); len(raw) > 0 {
		tmp.value = raw
	}
	*c = tmp
	return nil
}
