package slack

// Auto-generated by internal/cmd/genmethods/genmethods.go (generateServiceDetailsFile). DO NOT EDIT!

import (
	"context"
	"encoding/json"
	"net/url"
	"strconv"
	"strings"

	"github.com/lestrrat-go/slack/objects"
	"github.com/pkg/errors"
)

var _ = strconv.Itoa
var _ = strings.Index
var _ = json.Marshal
var _ = objects.EpochTime(0)

// UsergroupsUsersListCall is created by UsergroupsUsersService.List method call
type UsergroupsUsersListCall struct {
	service         *UsergroupsUsersService
	includeDisabled bool
	usergroup       string
}

// UsergroupsUsersUpdateCall is created by UsergroupsUsersService.Update method call
type UsergroupsUsersUpdateCall struct {
	service      *UsergroupsUsersService
	includeCount bool
	usergroup    string
	users        string // Comma-separated list of user IDs
}

// List creates a UsergroupsUsersListCall object in preparation for accessing the usergroups.users.list endpoint
func (s *UsergroupsUsersService) List(usergroup string) *UsergroupsUsersListCall {
	var call UsergroupsUsersListCall
	call.service = s
	call.usergroup = usergroup
	return &call
}

// IncludeDisabled sets the value for optional includeDisabled parameter
func (c *UsergroupsUsersListCall) IncludeDisabled(includeDisabled bool) *UsergroupsUsersListCall {
	c.includeDisabled = includeDisabled
	return c
}

// ValidateArgs checks that all required fields are set in the UsergroupsUsersListCall object
func (c *UsergroupsUsersListCall) ValidateArgs() error {
	if len(c.usergroup) <= 0 {
		return errors.New(`required field usergroup not initialized`)
	}
	return nil
}

// Values returns the UsergroupsUsersListCall object as url.Values
func (c *UsergroupsUsersListCall) Values() (url.Values, error) {
	if err := c.ValidateArgs(); err != nil {
		return nil, errors.Wrap(err, `failed validation`)
	}
	v := url.Values{}
	v.Set(`token`, c.service.token)

	if c.includeDisabled {
		v.Set("include_disabled", "true")
	}

	v.Set("usergroup", c.usergroup)
	return v, nil
}

type UsergroupsUsersListCallResponse struct {
	OK        bool                   `json:"ok"`
	ReplyTo   int                    `json:"reply_to"`
	Error     *objects.ErrorResponse `json:"error"`
	Timestamp string                 `json:"ts"`
	Payload0  json.RawMessage        `json:"-"`
	Payload1  json.RawMessage        `json:"users"`
}

func (r *UsergroupsUsersListCallResponse) parse(data []byte) error {
	if err := json.Unmarshal(data, r); err != nil {
		return errors.Wrap(err, `failed to unmarshal UsergroupsUsersListCallResponse`)
	}
	r.Payload0 = data
	return nil
}
func (r *UsergroupsUsersListCallResponse) payload() (objects.UsergroupUsersList, error) {
	var res1 objects.UsergroupUsersList
	if err := json.Unmarshal(r.Payload1, &res1); err != nil {
		return nil, errors.Wrap(err, `failed to ummarshal objects.UsergroupUsersList from response`)
	}
	return res1, nil
}

// Do executes the call to access usergroups.users.list endpoint
func (c *UsergroupsUsersListCall) Do(ctx context.Context) (objects.UsergroupUsersList, error) {
	const endpoint = "usergroups.users.list"
	v, err := c.Values()
	if err != nil {
		return nil, err
	}
	var res UsergroupsUsersListCallResponse
	if err := c.service.client.postForm(ctx, endpoint, v, &res); err != nil {
		return nil, errors.Wrap(err, `failed to post to usergroups.users.list`)
	}
	if !res.OK {
		var err error
		if errresp := res.Error; errresp != nil {
			err = errors.New(errresp.String())
		} else {
			err = errors.New(`unknown error while posting to usergroups.users.list`)
		}
		return nil, err
	}

	return res.payload()
}

// FromValues parses the data in v and populates `c`
func (c *UsergroupsUsersListCall) FromValues(v url.Values) error {
	var tmp UsergroupsUsersListCall
	if raw := strings.TrimSpace(v.Get("include_disabled")); len(raw) > 0 {
		parsed, err := strconv.ParseBool(raw)
		if err != nil {
			return errors.Wrap(err, `failed to parse boolean value "include_disabled"`)
		}
		tmp.includeDisabled = parsed
	}
	if raw := strings.TrimSpace(v.Get("usergroup")); len(raw) > 0 {
		tmp.usergroup = raw
	}
	*c = tmp
	return nil
}

// Update creates a UsergroupsUsersUpdateCall object in preparation for accessing the usergroups.users.update endpoint
func (s *UsergroupsUsersService) Update(usergroup string, users string) *UsergroupsUsersUpdateCall {
	var call UsergroupsUsersUpdateCall
	call.service = s
	call.usergroup = usergroup
	call.users = users
	return &call
}

// IncludeCount sets the value for optional includeCount parameter
func (c *UsergroupsUsersUpdateCall) IncludeCount(includeCount bool) *UsergroupsUsersUpdateCall {
	c.includeCount = includeCount
	return c
}

// ValidateArgs checks that all required fields are set in the UsergroupsUsersUpdateCall object
func (c *UsergroupsUsersUpdateCall) ValidateArgs() error {
	if len(c.usergroup) <= 0 {
		return errors.New(`required field usergroup not initialized`)
	}
	if len(c.users) <= 0 {
		return errors.New(`required field users not initialized`)
	}
	return nil
}

// Values returns the UsergroupsUsersUpdateCall object as url.Values
func (c *UsergroupsUsersUpdateCall) Values() (url.Values, error) {
	if err := c.ValidateArgs(); err != nil {
		return nil, errors.Wrap(err, `failed validation`)
	}
	v := url.Values{}
	v.Set(`token`, c.service.token)

	if c.includeCount {
		v.Set("include_count", "true")
	}

	v.Set("usergroup", c.usergroup)

	v.Set("users", c.users)
	return v, nil
}

type UsergroupsUsersUpdateCallResponse struct {
	OK        bool                   `json:"ok"`
	ReplyTo   int                    `json:"reply_to"`
	Error     *objects.ErrorResponse `json:"error"`
	Timestamp string                 `json:"ts"`
	Payload0  json.RawMessage        `json:"-"`
	Payload1  json.RawMessage        `json:"usergroup"`
}

func (r *UsergroupsUsersUpdateCallResponse) parse(data []byte) error {
	if err := json.Unmarshal(data, r); err != nil {
		return errors.Wrap(err, `failed to unmarshal UsergroupsUsersUpdateCallResponse`)
	}
	r.Payload0 = data
	return nil
}
func (r *UsergroupsUsersUpdateCallResponse) payload() (*objects.Usergroup, error) {
	var res1 objects.Usergroup
	if err := json.Unmarshal(r.Payload1, &res1); err != nil {
		return nil, errors.Wrap(err, `failed to ummarshal objects.Usergroup from response`)
	}
	return &res1, nil
}

// Do executes the call to access usergroups.users.update endpoint
func (c *UsergroupsUsersUpdateCall) Do(ctx context.Context) (*objects.Usergroup, error) {
	const endpoint = "usergroups.users.update"
	v, err := c.Values()
	if err != nil {
		return nil, err
	}
	var res UsergroupsUsersUpdateCallResponse
	if err := c.service.client.postForm(ctx, endpoint, v, &res); err != nil {
		return nil, errors.Wrap(err, `failed to post to usergroups.users.update`)
	}
	if !res.OK {
		var err error
		if errresp := res.Error; errresp != nil {
			err = errors.New(errresp.String())
		} else {
			err = errors.New(`unknown error while posting to usergroups.users.update`)
		}
		return nil, err
	}

	return res.payload()
}

// FromValues parses the data in v and populates `c`
func (c *UsergroupsUsersUpdateCall) FromValues(v url.Values) error {
	var tmp UsergroupsUsersUpdateCall
	if raw := strings.TrimSpace(v.Get("include_count")); len(raw) > 0 {
		parsed, err := strconv.ParseBool(raw)
		if err != nil {
			return errors.Wrap(err, `failed to parse boolean value "include_count"`)
		}
		tmp.includeCount = parsed
	}
	if raw := strings.TrimSpace(v.Get("usergroup")); len(raw) > 0 {
		tmp.usergroup = raw
	}
	if raw := strings.TrimSpace(v.Get("users")); len(raw) > 0 {
		tmp.users = raw
	}
	*c = tmp
	return nil
}
